version: '3.1'
services:
  gotenberg:
    image: gotenberg/gotenberg:7.7.0
    networks:
      - laa
    container_name: gotenberg
    ports:
      - "3100:3100"
    command:
      - "gotenberg"
      - "--api-port=3100"
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--pdfengines-engines=pdftk"
      - "--uno-listener-restart-threshold=0" #disables uno listener
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3100/health' ]

  redis:
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    image: redis:6.2
    networks:
      - laa
    ports:
      - '6379:6379'

networks:
  laa:
    
