version: '3.1'
services:

  wiremock:
    image: wiremock/wiremock
    networks:
    - laa_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"

  gotenberg:
    image: gotenberg/gotenberg:7.7.0
    networks:
      - laa_int
    container_name: gotenberg_int
    ports:
      - "3100:3100"
    command:
      - "gotenberg"
      - "--api-port=3100"
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--pdfengines-engines=pdftk"
      - "--uno-listener-restart-threshold=0" #disables uno listener
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3100/health' ]
networks:
  laa_int:
