services:
  app:
    build:
      context: .
    networks:
      - laa
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - SESSION_SECRET=somesecretvalue
      # To enable SSO, see instructions in README
      - SSO_DISABLED=true
  redis:
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    image: redis:7.4
    networks:
      - laa
    ports:
      - '6379:6379'

networks:
  laa:
