apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
  labels:
    app: laa-crime-equinity-historical-data-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-crime-equinity-historical-data-frontend # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: laa-crime-equinity-historical-data-frontend # this should match the selector in service.yml
    spec:
      containers:
        - name: eqmfrontend
          image: ${IMAGE_TAG}
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "ALL" ]
          env:
          - name: EQ_API_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: appsecret
                key: EQ_API_CLIENT_ID
          - name:  EQ_API_SECRET
            valueFrom:
              secretKeyRef:
                name: appsecret
                key: EQ_API_SECRET    
          - name:  EQ_SEARCH_API_URL
            valueFrom:
              secretKeyRef:
                name: appsecret
                key: EQ_SEARCH_API_URL    
