apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laa-crime-equinity-historical-data-frontend-ingress
  namespace: ${CP_NAMESPACE}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ${APP_NAME}-ingress-${CP_NAMESPACE}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"    
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: default    
  tls:
    - hosts:
        - ${CP_NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
  rules:
    - host: ${CP_NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: laa-crime-equinity-historical-data-frontend-service # this should match the metadata.name in service.yml
                port:
                  number: 3000
