apiVersion: v1
kind: Service
metadata:
  name: laa-crime-equinity-historical-data-frontend-service
spec:
  selector:
    app: laa-crime-equinity-historical-data-frontend # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 4000
      targetPort: 4000