apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:
  selector:
    app: laa-crime-equinity-historical-data-frontend # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 3000
      targetPort: 3000
