apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-deployment"
  namespace: "{{ .Chart.Name }}-{{ .Values.service.environment }}"
  labels:
    {{- include "laa-crime-equinity-historical-data-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laa-crime-equinity-historical-data-frontend.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laa-crime-equinity-historical-data-frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          {{ include "laa-crime-equinity-historical-data-frontend.env-vars" . | nindent 10 }}

# This is a generic file that creates a Kubernetes deployment in our namespace. A deployment is a collection of pods
# that runs one or more containers. In this application, currently only one container is run in the pod.