service:
  environment: "archive"

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-crime-equinity-historical-data-frontend-ingress-laa-crime-equinity-historical-data-frontend-archive-green

env:
  ENVIRONMENT_NAME: archive
  EQ_API_URL: https://laa-crime-equinity-historical-data-archive.apps.live.cloud-platform.service.justice.gov.uk
  SDS_API_URL: https://laa-sds-production.apps.live.cloud-platform.service.justice.gov.uk
