service:
  port: 3000

nameOverride: ""

image:
  # Override the image repository whose real value should come from secret.
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
  type:
    RuntimeDefault
  capabilities:
    drop: [ "ALL" ]

ingress:
  className: "default"
  annotations:
#    external-dns.alpha.kubernetes.io/set-identifier: {{ .Chart.Name }}-ingress-{{ .Chart.Name }}-{{ .Values.service.environment }}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: 188.214.15.75/32, 192.168.5.101/32,92.177.120.49/32,81.134.202.29/32,79.152.189.104/32,179.50.12.212/32,188.172.252.34/32,194.33.192.0/25,194.33.193.0/25,194.33.196.0/25,194.33.197.0/25,195.59.75.0/24,201.33.21.5/32,213.121.161.112/28,52.67.148.55/32,54.94.206.111/32,178.248.34.42/32,178.248.34.43/32,178.248.34.44/32,178.248.34.45/32,178.248.34.46/32,178.248.34.47/32,89.32.121.144/32,185.191.249.100/32,2.138.20.8/32,18.169.147.172/32,35.176.93.186/32,18.130.148.126/32,35.176.148.126/32,35.178.209.113/32,3.8.51.207/32,35.177.252.54/32,51.149.250.0/24,51.149.249.0/29,194.33.249.0/29,51.149.249.32/29,194.33.248.0/29,20.49.214.199/32,20.49.214.228/32,20.26.11.71/32,20.26.11.108/32,194.33.200.0/21,194.33.216.0/23,194.33.218.0/24,128.77.75.64/26
    nginx.ingress.kubernetes.io/server-snippet: |
      location @custom_403 {
        return 403 "<html> <head> <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'></head><body> <div class='container'> <div class='content'> <div class='title'>You are not authorised to access this application</div><div><br><br><b><a href='mailto:laa-eq-data-migration-team@digital.justice.gov.uk?subject=Access%20support%20request%20SOC%20Entry' target='_top'>Contact Us</a></b> if you have any queries</div></div></div></body></html>";
      }
      error_page 403 @custom_403;
  hosts:
    - host: apps.live.cloud-platform.service.justice.gov.uk
      paths: [ "/" ]
replicaCount: 1

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
autoscaling:
  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
# targetMemoryUtilizationPercentage: 80

podLabels: {}