apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: "{{ .Chart.Name }}-{{ .Values.service.environment }}"
  labels:
    {{- include "laa-crime-equinity-historical-data-frontend.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "laa-crime-equinity-historical-data-frontend.selectorLabels" . | nindent 4 }}
