name: Build and deploy after PR merged

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version'
        type: string
        required: false
        default: '20.x'
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME: "equinity-frontend"
  IMAGE_TAG: ${{ github.sha }} # Tags ECR image with commit sha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build

  unit-tests:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        id: unit-test
        uses: ./.github/actions/unit-test

  integration-tests:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        id: unit-test
        uses: ./.github/actions/integration-test

  ecr:
    runs-on: ubuntu-latest
    needs:
      - integration-tests
      - unit-tests
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      # Build and push docker image to container repo
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        with:
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          push: true

  deploy-dev:
    needs: ecr
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    uses: ./.github/workflows/_deploy-to.yml
    with:
      environment: "dev"
      repo_name: "equinity-frontend"
      app_name: "laa-crime-equinity-historical-data-frontend"
    secrets: inherit
    
  deploy-uat:
    needs: deploy-dev
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    uses: ./.github/workflows/_deploy-to.yml
    with:
      environment: "uat"
      repo_name: "equinity-frontend"
      app_name: "laa-crime-equinity-historical-data-frontend"
    secrets: inherit
  
  deploy-archive:
    needs: deploy-uat
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    uses: ./.github/workflows/_deploy-to.yml
    with:
      environment: "archive"
      repo_name: "equinity-frontend"
      app_name: "laa-crime-equinity-historical-data-frontend"
    secrets: inherit

  deploy-prod:
    needs: deploy-uat
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
      packages: write
    uses: ./.github/workflows/_deploy-to.yml
    with:
      environment: "prod"
      repo_name: "equinity-frontend"
      app_name: "laa-crime-equinity-historical-data-frontend"
    secrets: inherit
